# Generated by Django 5.0.4 on 2024-05-02 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "category",
            },
        ),
        migrations.CreateModel(
            name="telephone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=150)),
                ("company", models.CharField(max_length=180)),
                ("price", models.IntegerField()),
                ("info", models.CharField(max_length=250)),
                ("image", models.ImageField(blank=True, null=True, upload_to="media/")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.category"
                    ),
                ),
            ],
            options={
                "db_table": "telephone",
            },
        ),
    ]
